apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
#  namespace: my-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: db
            - name: MYSQL_ROOT_PASSWORD
              value: password
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 15
            periodSeconds: 20
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
  selector:
    matchLabels:
      app: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
#  namespace: my-app
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql