apiVersion: v1
kind: Pod
metadata:
  name: python-app
#  namespace: my-app
spec:
  containers:
    - name: python-app
      image: gcr.io/utopian-goods-272809/python-app:0.1
      ports:
        - containerPort: 80
