apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
#  namespace: my-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: gcr.io/utopian-goods-272809/python-app:0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: REDIS_NAME
              value: redis
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
      initContainers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
          command: ['sh', '-c', 'until redis-cli -p 6379 ping; do echo waiting for redis; sleep 2; done;']
  selector:
    matchLabels:
      app: python-app